server:
  port:
    8090

spring:
  application:
    name:
      MyOtaApp

logging:
  level:
    com:
      online:
        travel:
          INFO
  file:
    clean-history-on-start:
      true
    name:
      logs/${spring.application.name}.log  

application-description:
  @project.description@
application-version:
  @project.version@
springdoc.use-fqn:
  true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  static:
    basePath: /
  enabled: true

air:
  shop:
    url:
      http://iata.api.mashery.com/athena/ndc192api
    maxOffers: 25
    maxSegments: 25
  offer:
    url:
      http://iata.api.mashery.com/athena/ndc192api